node("master") {
  checkout scm

  version = '1.0-SNAPSHOT'

  stage('Build site') {
    sh 'cd my-app && ./gradlew build'

    println "my-app/target/my-app-${version}.jar"
    archiveArtifacts artifacts: "my-app/target/*.jar", fingerprint: false
  }

  input id: 'ID', message: 'Continue?', ok: 'Yes', parameters: [choice(choices: ['YES', 'NO'], description: '', name: 'Choice')], submitter: 'admin', submitterParameter: 'choice'

 /*
  node("DockerNode") {
     env.PATH = "/usr/local/bin:${env.PATH}"

     stage('Inside Docker') {
       timeout(160) {
         img = docker.image("openjdk:8")

         img.inside() {
           checkout scm

           sh 'hostname'
           sh 'ls -l my-app'
           sh 'cd my-app && ./gradlew build'
         }
       }
     }
  }
*/
}
