node("master") {
  checkout scm

  version = '1.0-SNAPSHOT'

  stage('Build site') {
    sh 'cd my-app && ./gradlew build'

    println "my-app/target/my-app-${version}.jar"
    archiveArtifacts artifacts: "my-app/target/*.jar", fingerprint: false
  }

  stage("Confirm") {
    input id: 'ID', message: 'Continue?', ok: 'Yes'
  }

  stage("Parallel tests") {
    // a loop counter of 131072 didn't yet show the error
    def parallels =  [
      '0': { node('master') {
        println "Execute 0"
        sh 'sleep 60'
       }},
       '1': { node('master') {
        println "Execute 1"
        sh 'sleep 60'
       }},
       '2': { node('master') {
        println "Execute 2"
        sh 'sleep 60'
       }} ,
       '3': { node('master') {
        println "Execute 3"
        sh 'sleep 60'
    }}
    ]

    parallel parallels
  }
}
 /*
  node("DockerNode") {
     env.PATH = "/usr/local/bin:${env.PATH}"

     stage('Inside Docker') {
       timeout(160) {
         img = docker.image("openjdk:8")

         img.inside() {
           checkout scm

           sh 'hostname'
           sh 'ls -l my-app'
           sh 'cd my-app && ./gradlew build'
         }
       }
     }
  }
*/
